### ISSUE TITLE
[Task]: Refactor and cleanup Redis connector code base 

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#4949]
### Connector Name

module/redis (Redis)

### Task Description

The current connector is outdated in both API and Ballerina aspects. The SDK version which is used to implement is 2018 released version. The implementation of java interoperability could also improve using latest ballerina features.

- [x] Update lettuce to latest version
- [x] Refactor the java interoperability implementation
- [x] Remove the usage of deprecated `ErrorCreator.createDistinctError` method usage
- [x] Remove redundant methods calls in the native implementation

**Comment by NipunaRanasinghe** [comment]
Closing as the related changes are merged with https://github.com/ballerina-platform/module-ballerinax-redis/pull/197
