### ISSUE TITLE
[Task]: Revamp microsoft excel connector 

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-library#4952]
### Connector Name

module/microsoft-excel (MS Excel)

### Task Description

This is the main task to revamp the existing Ballerina Salesforce connector.
- [x] Go through the existing APIs and come up with the draft design
- [x] Go through the connector and identify issues and possible improvements
- [x] Implement the connector

**Comment by kalaiyarasiganeshalingam** [comment]
API doc: https://docs.google.com/document/d/1fBezZq4cSyjDjJvuIl3ZGKSBCVFV1n-H7MdsLWShvjo/edit?usp=sharing

**Comment by kalaiyarasiganeshalingam** [comment]
Created the issue to generate custom headers and query parameters: https://github.com/ballerina-platform/ballerina-library/issues/5820
