### ISSUE TITLE
[Epic]: Include examples for the modules that are currently lacking them

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-library#4968]
### Connector Name

connectors/samples (Connector Samples/Templates)

### Epic description

Currently, the following Ballerina modules lack any examples. Once the examples are added, the GitHub workflows should be updated to build them in a manner similar to how it's done for other modules. (Comparable to what has been done here: [Github Workflows](https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar/tree/main/.github/workflows))

- [ ] [module-ballerinax-github](https://github.com/ballerina-platform/module-ballerinax-github)
- [ ]  [module-ballerinax-azure-storage-service](https://github.com/ballerina-platform/module-ballerinax-azure-storage-service)
- [ ]  [module-ballerinax-mongodb](https://github.com/ballerina-platform/module-ballerinax-mongodb)
- [ ]  [module-ballerinax-aws.ses](https://github.com/ballerina-platform/module-ballerinax-aws.ses)
- [ ]  [module-ballerinax-peoplehr](https://github.com/ballerina-platform/module-ballerinax-peoplehr)
- [ ]  [module-ballerinax-aws.simpledb](https://github.com/ballerina-platform/module-ballerinax-aws.simpledb)
- [ ]  [module-ballerinax-aws.dynamodb](https://github.com/ballerina-platform/module-ballerinax-aws.dynamodb)

**Comment by ThisaruGuruge** [comment]
This is tracked via the connector revamping process. Some of the mentioned connectors already added examples and they have been added to the builds. Therefore closing the issue.
