### ISSUE TITLE
[Epic]: Design and implement WSDL to Ballerina client generator

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-library#5045]
### Connector Name

other (None Listed Above)

### Epic description

WSDL is an XML based web service definition that provides the functionality of the web service exposed by the service provider. In many languages, clients can be created from WSDL and accessed.
Currently, Ballerina does not have a tool to generate client connectors from WSDL.

### Related tasks

- [x] **Research on WSDL, SOAP, DOM and SAX domains** 
- [x] **Prepare design document**
- [x] **Prepare mapping between WSDL and Ballerina**
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/5012
- [ ] https://github.com/ballerina-platform/ballerina-standard-library/issues/5009

**Comment by SanduDS** [comment]
Closing as this will not be done.
