### ISSUE TITLE
Write the specification for Ballerina OpenAPI Tool

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#5132]
**Task list**

- [x] ballerina-platform/ballerina-standard-library#5128
- [ ] ballerina-platform/ballerina-standard-library#5125
- [ ] ballerina-platform/ballerina-standard-library#5127
- [x] ballerina-platform/ballerina-standard-library#5126

**Comment by lnash94** [comment]
Duplicate: https://github.com/ballerina-platform/ballerina-library/issues/5128
