### ISSUE TITLE
[Epic]: Revamp Azure Service Bus Connector

### ISSUE THREAD

**Issue by RDPerera** [ballerina-platform/ballerina-library#5807]
### Connector Name

[ballerinax/asb](https://github.com/ballerina-platform/module-ballerinax-azure-service-bus) [(Azure Service Bus)](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview)

The [Azure Service Bus](https://azure.microsoft.com/en-us/services/service-bus/) is a reliable cloud Messaging as a Service (Maas). It is an enterprise message broker with message queues and publish-subscribe topics. The service bus is used to decouple applications and services from each other. Data is transferred between different applications and services using messages. You can find more information [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/).

The Azure Service Bus [Ballerina](https://ballerina.io/) connector allows you to connect to the Azure Service Bus to send and receive messages. You can perform actions such as send to queue, send to topic, receive from queue, receive from subscription, and admin operations.

### Task Description

Revamping the existing Ballerina ASB connector involves following sub tasks

- [x]  Migrating connector repository to gradle
- [x]  Add GraalVM compatibility and observability 
- [x]  Update the documentation

**Comment by RDPerera** [comment]
As it's completed
