### ISSUE TITLE
Add support for SSL in Redshift connector

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-library#5923]
**Description:**
Implement SSL support in the Ballerina Redshift Connector to enable secure communication with Amazon Redshift databases.

To enable SSL in connections you have to set the `ssl` property to `true`. Redshift supports following `ssl modes`, which will be exposed in our ballerina clients. 
```
disable - SSL is disabled and the connection is not encrypted.

allow - SSL is used if the server requires it.

prefer - SSL is used if the server supports it. Amazon Redshift supports SSL, so SSL is used when you set sslmode to prefer.

require - SSL is required.

verify-ca - SSL must be used and the server certificate must be verified.

verify-full - SSL must be used. The server certificate must be verified and the server hostname must match the hostname attribute on the certificate.
```
**API Design**

```ballerina

# Possible values for the SSL mode.
public enum SSLMode {
    PREFER = "prefer",
    REQUIRE = "require",
    DISABLE = "disable",
    ALLOW = "allow",
    VERIFY_CA = "verify-ca",
    VERIFY_FULL = "verify-full"
}
```

Sample connection:

```ballerina
redshift:Options connectionOptions = {
       sslmode: redshift:VERIFY_FULL,
};

// Initialize the Redshift client
redshift:Client dbClient = check new (jdbcUrl, user, password, options = connectionOptions);
```

**Task Breakdown**
- [x] Design and implement the SSL support in Redshift Connector
- [x] Test positive use cases
- [ ] Test negative use cases
- [ ] Testing each ssl mode

**Referencecs:**
1. How to enable SSL in the server: https://www.intelligentdiscovery.io/controls/redshift/aws-redshift-enforce-ssl
2. Connecting with SSL: https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html
