### ISSUE TITLE
[Epic] WSDL-Tools Improvements

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-library#6822]
**Description:**
This issue is to capture the known improvements to be made in the WSDL tools

- [ ] Implement the tool to support multiple service definitions in a WSDL spec.
- [ ] Handle the scenario when Messages have inline types instead of referred types
- [ ] Handle external WSDL imports (maybe less priority)
- [ ] Mode XSD to Record generator as a standalone implementation as this is a common use case other than WSDL parsing
- [ ] When processing SimpleType Schema, Handle SimpleTypeList & SimpleTypeUnion as well
- [ ] When processing SimpleContent Schema, Handle SimpleContentRestriction as well
- [ ] When processing particles, process AnyAttribute Schema as well
- [ ] When processing particles, process SchemaAll & SchemaChoice Schemas as well
- [ ] When processing facets(used in XSD for restriction on SimpleTypes) handle all the cases other than enum facet

**Comment by daneshk** [comment]
@Nuvindu, Can you check this and close if this is already done

**Comment by Nuvindu** [comment]
Currently, importing WSDL files from external sources is not supported. Since there hasn’t been a requirement for this feature so far, it hasn’t been implemented. If a need arises, we can consider adding support for it in the future.
