### ISSUE TITLE
[Milestone 1][Generated connectors] Listing Ballerina packages on relevant tech-documentations

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#7332]
### Description
> $subject

Timeframe: 05th November, 2024 to 18th November, 2024

In this phase we will work on the Ballerina generated connectors which needs to be listed on the official documentation. In this milestone, we need to start working on the following connectors.

- [x] **asana**              - @NipunaRanasinghe @ayeshLK 
- [x] **candid**             - @AzeemMuzammil
- [x] **dayforce**           - @RDPerera
- [x] **discord**            - @RDPerera @ayeshLK 
- [x] **docusign.dsadmin**   - @Nuvindu
- [x] **docusign.dsclick**   - @Nuvindu
- [x] **docusign.dsesign**   - @Nuvindu
- [x] **github**             - @AzeemMuzammil
- [x] **googleapis.calendar**- @Nuvindu
- [x] **googleapis.gmail**   - @Niveathika @lnash94 
- [x] **guidewire.insnow**   - @ayeshLK
- [x] **openai.assistants**  - @SachinAkash01 
- [x] **openai.audio**       - @SachinAkash01
- [x] **openai.chat**        - @SachinAkash01
- [x] **openai.finetunes**   - @SachinAkash01
- [x] **openai.images**      - @SachinAkash01
- [x] **sap.s4hana.sales**   - @niveathika @lnash94
- [x] **slack**              - @RDPerera
- [x] **stripe**             - @ayeshLK
- [x] **twilio**             - @RDPerera @ayeshLK 
- [x] **twitter**            - @RDPerera @ayeshLK
- [x] **zendesk**            - @NipunaRanasinghe

**Comment by SachinAkash01** [comment]
I have put this effort on hold due to some required fixes for the U11, couldn't conduct a deep research on this. I will continue to work on this once the U11 tasks are completed..

**Comment by SachinAkash01** [comment]
> I have put this effort on hold due to some required fixes for the U11, couldn't conduct a deep research on this. I will continue to work on this once the U11 tasks are completed..

I have started working on this effort back again and I have filled and submitted the OpenAI Community Libraries Request Form [1] and have also sent an email to OpenAI Support regarding this. Waiting for their reply..

[1] - https://share.hsforms.com/1y0Ixew-rQOOZisFfnhszVA4sk30

**Comment by SachinAkash01** [comment]
> > I have put this effort on hold due to some required fixes for the U11, couldn't conduct a deep research on this. I will continue to work on this once the U11 tasks are completed..
> 
> I have started working on this effort back again and I have filled and submitted the OpenAI Community Libraries Request Form [1] and have also sent an email to OpenAI Support regarding this. Waiting for their reply..
> 
> [1] - https://share.hsforms.com/1y0Ixew-rQOOZisFfnhszVA4sk30

Got a reply from the OpenAI team and they informed me that they are reviewing each of our connectors individually and if those meet their criteria, they will reach out to me with the next steps to get our connectors listed.

**Comment by AzeemMuzammil** [comment]
I wan't able to start on the effort as I was occupied with AI Panel works, this was bit urgent as it had to go for beta release, and I was in my annuals for last two weeks,

**Comment by ayeshLK** [comment]
This task is now completed. Progress can be seen the **[Listing][M1] Connectors - Phase 1** of this google sheet [1]

[1] - https://docs.google.com/spreadsheets/d/1ftoU_BeJui0OV1zUwW8x80JO6bb48Lxgubs6PNmrcMM/edit?usp=sharing
