### ISSUE TITLE
[Milestone 2][Handwritten connectors] Listing Ballerina packages on relevant tech-documentations

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#7375]
### Description
> $subject

Timeframe: 19th November, 2024 to 2nd December, 2024

In this phase we will work on the Ballerina handwritten connectors which needs to be listed on the official documentation. In this milestone, we need to start working on the following connectors.

- [x] **aws.dynamodb** - @lnash94  
- [x] **aws.dynamodbstreams** - @lnash94  
- [ ] **aws.redshift** - @aashikam  
- [x] **aws.sns** - @TharmiganK  
- [x] **aws.marketplace entitlement** - @ayeshLK  
- [x] **aws.marketplace metering** - @ayeshLK  
- [x] **azure-service-bus** - @ayeshLK  
- [x] **confluent.cavroserdes** - @Nuvindu  
- [x] **confluent.cregistry** - @Nuvindu  
- [x] **ibm.ibmmq** - @ayeshLK  
- [x] **java.jdbc** - @niveathika  @SachinAkash01 
- [x] **java.jms** - @ayeshLK  
- [ ] **kafka** - @ThisaruGuruge  
- [x] **mssql** - @niveathika  @SachinAkash01 
- [x] **mysql** - @niveathika @SachinAkash01  
- [x] **oracledb** - @niveathika @SachinAkash01  
- [x] **postgresql** - @aashikam  
- [ ] **salesforce** - @aashikam  
- [x] **sap** - @niveathika @SachinAkash01  
- [x] **sap.jco** - @RDPerera  
- [ ] **snowflake** - @daneshk

**Comment by daneshk** [comment]
This task is done. Hence closing the issue
