### ISSUE TITLE
[Milestone 3][Standard Libraries] Listing Ballerina packages on relevant tech-documentations

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#7458]
### Description
> $subject

Timeframe: 11th December, 2024 to 20th December, 2024

In this phase we will work on the Ballerina standard which needs to be listed on the official documentation. In this milestone, we need to start working on the following standard libraries.

- [ ] **io** - @NipunaRanasinghe 
- [ ] **java.arrays** - @NipunaRanasinghe
- [ ] **math.vector** - @ayeshLK 
- [ ] **time** - @TharmiganK 
- [ ] **url** - @TharmiganK
- [x] **ldap** - @Nuvindu 
- [ ] **avro** - @Nuvindu
- [ ] **constraint** - @TharmiganK
- [x] **crypto** - @MohamedSabthar 
- [ ] **log** - @TharmiganK
- [ ] **os** - @MohamedSabthar
- [ ] **random** - @aashikam 
- [ ] **task** - @RDPerera 
- [ ] **xslt** - @Nuvindu
- [ ] **persist** - @TharmiganK
- [ ] **protobuf** - @TharmiganK
- [ ] **cache** - @NipunaRanasinghe
- [ ] **file** - @ayeshLK
- [ ] **uuid** - @aashikam
- [ ] **mime** - @MohamedSabthar
- [ ] **tcp** - @DimuthuMadushan 
- [ ] **udp** - @DimuthuMadushan
- [ ] **ftp** - @MohamedSabthar
- [x] **auth** - @DimuthuMadushan @MohamedSabthar 
- [x] **jwt** - @ayeshLK
- [x] **oauth2** - @MohamedSabthar
- [ ] **toml** - @RDPerera
- [ ] **yaml** - @RDPerera
- [x] **mqtt** - @ayeshLK
- [ ] **edi** - @RDPerera
- [x] **email** - @ayeshLK
- [ ] **http** - @TharmiganK
- [ ] **soap** - @Nuvindu
- [x] **websub** - @ayeshLK
- [x] **websubhub** - @ayeshLK
- [x] **sql** - @RDPerera
